function Hd = butter_filter(N,Fs,Fc)
%BUTTER_FILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.7 and Signal Processing Toolbox 8.3.
% Generated on: 20-Jul-2020 18:28:50

% Butterworth Lowpass filter designed using FDESIGN.LOWPASS.

% All frequency values are in Hz.
%{
Fs = 16000;  % Sampling Frequency

N  = 10;   % Order
Fc = 400;  % Cutoff Frequency
%}

% Construct an FDESIGN object and call its BUTTER method.
h  = fdesign.lowpass('N,F3dB', N, Fc, Fs);
Hd = design(h, 'butter');

% [EOF]
end
