function Hd = FIR_Kaiser2(N,Fs,Fc1,Fc2,flag,Beta)
    %FIR KAISER 2 Returns a discrete-time filter object.

    % MATLAB Code
    % Generated by MATLAB(R) 9.8 and Signal Processing Toolbox 8.4.
    % Generated on: 18-Jul-2020 19:42:56

    % FIR Window Bandpass filter designed using the FIR1 function.
    %{
    % All frequency values are in Hz.
    Fs = 16000;  % Sampling Frequency
    N    = 100;      % Order
    Fc1  = 100;      % First Cutoff Frequency
    Fc2  = 1000;     % Second Cutoff Frequency
    flag = 'scale';  % Sampling Flag
    Beta = 6;        % Window Parameter
    %}
    % Create the window vector for the design algorithm.
    win = kaiser(N+1, Beta);

    % Calculate the coefficients using the FIR1 function.
    b  = fir1(N, [Fc1 Fc2]/(Fs/2), 'bandpass', win, flag);
    Hd = dfilt.dffir(b);
end
% [EOF]